"""Abstract base class and response models for LLM providers (Phase 8)."""

from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class LLMResponse(BaseModel):
    """Normalized response schema from any LLM provider."""

    content: str = Field(description="The primary text response content generated by the model.")
    model_name: str = Field(description="The exact model identifier used for generation.")
    provider_name: str = Field(description="The provider identifier (e.g. gemini, anthropic, openai).")
    prompt_tokens: Optional[int] = Field(default=None, description="Number of tokens in prompt if available.")
    completion_tokens: Optional[int] = Field(default=None, description="Number of tokens in completion if available.")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Provider-specific raw metadata.")


class LLMProvider(ABC):
    """Abstract interface decoupling business/reasoning logic from specific LLM vendors.
    
    CRITICAL ARCHITECTURAL BOUNDARY:
    The LLM is strictly responsible for:
    - Natural language understanding
    - Clarification questions
    - Conversational response synthesis
    - Human-readable explanation rendering
    
    The LLM is NEVER the scientific source of truth or calculation engine.
    """

    @property
    @abstractmethod
    def provider_name(self) -> str:
        """Name of the LLM provider."""
        pass

    @property
    @abstractmethod
    def default_model(self) -> str:
        """Default model identifier."""
        pass

    @abstractmethod
    def generate(
        self,
        prompt: str,
        system_instruction: Optional[str] = None,
        temperature: float = 0.2,
        max_tokens: Optional[int] = None,
    ) -> LLMResponse:
        """Generate a response synchronously."""
        pass

    @abstractmethod
    async def generate_async(
        self,
        prompt: str,
        system_instruction: Optional[str] = None,
        temperature: float = 0.2,
        max_tokens: Optional[int] = None,
    ) -> LLMResponse:
        """Generate a response asynchronously."""
        pass

