"""Curated authentic scientific evidence metadata for the Ecological Knowledge Base (Phase 3).

All citations are sourced from peer-reviewed syntheses and official institutional
assessments (IPCC, IPBES, FAO, UNEP, CBD). No citations, statistics, or DOIs are fabricated.
"""

from typing import List
from backend.app.schemas.knowledge import EvidenceMetadata

CURATED_EVIDENCE: List[EvidenceMetadata] = [
    EvidenceMetadata(
        id="FAO_SOIL_2020",
        source_type="institutional_report",
        citation="FAO, ITPS, GSBI, SCBD (2020). State of knowledge of soil biodiversity - Status, challenges and potentialities. Food and Agriculture Organization of the United Nations, Rome.",
        doi="10.4060/cb1928en",
        year=2020,
        institution="FAO",
        url="https://www.fao.org/documents/card/en/c/cb1928en",
        requires_evidence=False,
        confidence_grade="high",
    ),
    EvidenceMetadata(
        id="IPBES_GLOBAL_2019",
        source_type="institutional_report",
        citation="IPBES (2019). Global assessment report on biodiversity and ecosystem services of the Intergovernmental Science-Policy Platform on Biodiversity and Ecosystem Services. Brondizio E.S. et al. (eds). IPBES secretariat, Bonn, Germany.",
        doi="10.5281/zenodo.3831673",
        year=2019,
        institution="IPBES",
        url="https://ipbes.net/global-assessment",
        requires_evidence=False,
        confidence_grade="high",
    ),
    EvidenceMetadata(
        id="IPCC_WG2_2022_CH2",
        source_type="institutional_report",
        citation="IPCC (2022). Climate Change 2022: Impacts, Adaptation and Vulnerability. Chapter 2: Terrestrial and Freshwater Ecosystems and their Services. Cambridge University Press, Cambridge, UK and New York, NY, USA.",
        doi="10.1017/9781009325844.004",
        year=2022,
        institution="IPCC",
        url="https://www.ipcc.ch/report/ar6/wg2/chapter/chapter-2/",
        requires_evidence=False,
        confidence_grade="high",
    ),
    EvidenceMetadata(
        id="IPCC_SRCCL_2019",
        source_type="institutional_report",
        citation="IPCC (2019). Climate Change and Land: an IPCC special report on climate change, desertification, land degradation, sustainable land management, food security, and greenhouse gas fluxes in terrestrial ecosystems. Shukla P.R. et al. (eds).",
        doi=None,
        year=2019,
        institution="IPCC",
        url="https://www.ipcc.ch/srccl/",
        requires_evidence=False,
        confidence_grade="high",
    ),
    EvidenceMetadata(
        id="UNEP_LAND_DEGRAD_2021",
        source_type="institutional_report",
        citation="UNEP (2021). Making Peace with Nature: A scientific blueprint to tackle the climate, biodiversity and pollution emergencies. United Nations Environment Programme, Nairobi.",
        doi=None,
        year=2021,
        institution="UNEP",
        url="https://www.unep.org/resources/making-peace-nature",
        requires_evidence=False,
        confidence_grade="high",
    ),
    EvidenceMetadata(
        id="LAL_2004_CARBON",
        source_type="peer_reviewed",
        citation="Lal, R. (2004). Soil carbon sequestration impacts on global climate change and food security. Science, 304(5677), 1623-1627.",
        doi="10.1126/science.1097396",
        year=2004,
        institution="Science",
        url="https://doi.org/10.1126/science.1097396",
        requires_evidence=False,
        confidence_grade="high",
    ),
    EvidenceMetadata(
        id="TILMAN_2014_BIODIV",
        source_type="peer_reviewed",
        citation="Tilman, D., Isbell, F., & Cowles, J. M. (2014). Biodiversity and ecosystem functioning. Annual Review of Ecology, Evolution, and Systematics, 45, 471-493.",
        doi="10.1146/annurev-ecolsys-120213-091917",
        year=2014,
        institution="Annual Reviews",
        url="https://doi.org/10.1146/annurev-ecolsys-120213-091917",
        requires_evidence=False,
        confidence_grade="high",
    ),
    EvidenceMetadata(
        id="HOOPER_2005_SYNTHESIS",
        source_type="systematic_review",
        citation="Hooper, D. U., et al. (2005). Effects of biodiversity on ecosystem functioning: a consensus of current knowledge. Ecological Monographs, 75(1), 3-35.",
        doi="10.1890/04-0922",
        year=2005,
        institution="Ecological Society of America",
        url="https://doi.org/10.1890/04-0922",
        requires_evidence=False,
        confidence_grade="high",
    ),
    EvidenceMetadata(
        id="HADDAD_2015_FRAGMENTATION",
        source_type="peer_reviewed",
        citation="Haddad, N. M., et al. (2015). Habitat fragmentation and its lasting impact on Earth's ecosystems. Science Advances, 1(2), e1500052.",
        doi="10.1126/sciadv.1500052",
        year=2015,
        institution="Science Advances",
        url="https://doi.org/10.1126/sciadv.1500052",
        requires_evidence=False,
        confidence_grade="high",
    ),
    EvidenceMetadata(
        id="CBD_GBO5_2020",
        source_type="institutional_report",
        citation="Secretariat of the Convention on Biological Diversity (2020). Global Biodiversity Outlook 5. Montreal, Canada.",
        doi=None,
        year=2020,
        institution="CBD",
        url="https://www.cbd.int/gbo5",
        requires_evidence=False,
        confidence_grade="high",
    ),
    EvidenceMetadata(
        id="RAWLS_2003_SOIL_WATER",
        source_type="peer_reviewed",
        citation="Rawls, W. J., Pachepsky, Y. A., Ritchie, J. C., Sobecki, T. M., & Bloodworth, H. (2003). Effect of soil organic carbon on soil water retention. Geoderma, 116(1-2), 61-76.",
        doi="10.1016/S0016-7061(03)00094-6",
        year=2003,
        institution="Geoderma",
        url="https://doi.org/10.1016/S0016-7061(03)00094-6",
        requires_evidence=False,
        confidence_grade="high",
    ),
    EvidenceMetadata(
        id="PENN_2019_PH_NUTRIENTS",
        source_type="peer_reviewed",
        citation="Penn, C. J., & Camberato, J. J. (2019). A critical review on soil chemical processes that govern how soil pH affects phosphorus availability to plants. Agriculture, 9(6), 120.",
        doi="10.3390/agriculture9060120",
        year=2019,
        institution="Agriculture",
        url="https://doi.org/10.3390/agriculture9060120",
        requires_evidence=False,
        confidence_grade="high",
    ),
    EvidenceMetadata(
        id="TSCHARNTKE_2012_LANDSCAPE",
        source_type="systematic_review",
        citation="Tscharntke, T., et al. (2012). Landscape moderation of biodiversity patterns and processes - eight hypotheses. Biological Reviews, 87(3), 661-685.",
        doi="10.1111/j.1469-185X.2011.00216.x",
        year=2012,
        institution="Biological Reviews",
        url="https://doi.org/10.1111/j.1469-185X.2011.00216.x",
        requires_evidence=False,
        confidence_grade="high",
    ),
    EvidenceMetadata(
        id="BENTON_2003_FARMLAND",
        source_type="peer_reviewed",
        citation="Benton, T. G., Vickery, J. A., & Wilson, J. D. (2003). Farmland biodiversity: is habitat heterogeneity the key? Trends in Ecology & Evolution, 18(4), 182-188.",
        doi="10.1016/S0169-5347(03)00011-9",
        year=2003,
        institution="Trends in Ecology & Evolution",
        url="https://doi.org/10.1016/S0169-5347(03)00011-9",
        requires_evidence=False,
        confidence_grade="high",
    ),
]
