"""Pydantic schemas for Structured Ecological Findings, Conflicts, and Pipeline Requests (Phase 9)."""

from enum import Enum
from typing import Any, Dict, List, Optional, Union
from pydantic import BaseModel, Field, ConfigDict
from datetime import datetime

from backend.app.schemas.environmental_state import EnvironmentalState, SpatialContext
from backend.app.schemas.dataset import VariableProvenance, DataQualityReport
from backend.app.schemas.knowledge import (
    ReasoningChain,
    VariableObservationState,
    VariableStatus,
)
from backend.app.schemas.scientific_rag import EvidenceChunkPacket, NaturePressureSeverity


class ObservationSource(str, Enum):
    """Source provenance classification for an environmental observation."""

    USER_SUPPLIED = "user_supplied"
    DATASET_DERIVED = "dataset_derived"
    INFERRED = "inferred"
    UNKNOWN = "unknown"


class ConflictType(str, Enum):
    """Type of conflict or uncertainty identified during ecological evaluation."""

    USER_DATASET_DISCREPANCY = "user_dataset_discrepancy"
    GEOGRAPHIC_MISMATCH = "geographic_mismatch"
    TEMPORAL_OUTDATED = "temporal_outdated"
    CONFLICTING_EVIDENCE = "conflicting_evidence"
    MISSING_KEY_VARIABLES = "missing_key_variables"
    INSUFFICIENT_EVIDENCE = "insufficient_evidence"


class ConflictResolutionStrategy(str, Enum):
    """Strategy applied when resolving or recording conflicting data points."""

    USER_PREFERRED_WITH_UNCERTAINTY = "user_preferred_with_uncertainty"
    DATASET_PREFERRED = "dataset_preferred"
    PRESERVED_UNCERTAINTY = "preserved_uncertainty"
    AVERAGED = "averaged"


class ConflictReport(BaseModel):
    """Structured report on data discrepancies, geographic mismatches, or evidence contradictions."""

    model_config = ConfigDict(extra="forbid")

    conflict_id: str = Field(description="Unique conflict identifier, e.g. 'CONF_SOIL_PH_MISMATCH'")
    conflict_type: ConflictType = Field(description="Classification of conflict")
    variables_involved: List[str] = Field(description="List of metric IDs affected, e.g. ['soil.ph']")
    user_value: Optional[Any] = Field(default=None, description="Value supplied by user or text extract")
    dataset_value: Optional[Any] = Field(default=None, description="Value obtained from authoritative datasets")
    delta_percentage: Optional[float] = Field(default=None, description="Percentage discrepancy if numeric")
    message: str = Field(description="Detailed explanation of the discrepancy or mismatch")
    resolution_strategy: ConflictResolutionStrategy = Field(
        default=ConflictResolutionStrategy.USER_PREFERRED_WITH_UNCERTAINTY,
        description="How the pipeline resolved or accounted for the conflict",
    )
    uncertainty_penalty: float = Field(
        default=0.1,
        ge=0.0,
        le=1.0,
        description="Confidence penalty applied to downstream findings due to this conflict",
    )


class VariableFindingDetail(BaseModel):
    """Granular detail of an environmental metric participating in an ecological finding."""

    model_config = ConfigDict(extra="forbid")

    variable_id: str = Field(description="Canonical metric identifier, e.g. 'soil.ph'")
    name: str = Field(description="Human-readable variable name")
    value: Optional[Any] = Field(default=None, description="Observed or derived metric value")
    unit: Optional[str] = Field(default=None, description="Physical unit")
    source: ObservationSource = Field(description="Origin: user_supplied | dataset_derived | inferred | unknown")
    dataset_id: Optional[str] = Field(default=None, description="Authoritative dataset ID if dataset-derived")
    is_synthetic: bool = Field(default=False, description="True if filled via synthetic fallback")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Measurement reliability/confidence score")


class EcologicalFinding(BaseModel):
    """Structured ecological finding generated by multi-metric reasoning and grounded in scientific RAG."""

    model_config = ConfigDict(extra="forbid")

    finding_id: str = Field(description="Unique finding identifier, e.g. 'FINDING_WATER_CLIMATE_STRESS'")
    title: str = Field(description="Concise scientific title of the ecological finding")
    domain: str = Field(description="Domain: soil_health | water_climate | biodiversity_trophic | land_degradation | anthropogenic_pressure")
    severity: NaturePressureSeverity = Field(description="Severity: critical | high | medium | low")
    contributing_variables: List[str] = Field(description="List of environmental metrics contributing to this finding (3+ for compound rules)")
    variable_details: List[VariableFindingDetail] = Field(description="Detailed provenance and values of contributing metrics")
    inferred_pressure: str = Field(description="Identified ecological pressure or driver")
    ecological_mechanism: str = Field(description="Biophysical causal mechanism explaining why this pressure occurs")
    supporting_relationships: List[str] = Field(description="IDs of structured ecological relationships triggered in knowledge base")
    reasoning_chain: Optional[ReasoningChain] = Field(default=None, description="Step-by-step causal chain from observed state to pressure")
    uncertainty_level: str = Field(default="low", description="low | medium | high")
    uncertainty_factors: List[str] = Field(default_factory=list, description="Explicit factors contributing to uncertainty")
    conflict_flags: List[str] = Field(default_factory=list, description="IDs of any data conflicts associated with this finding")
    confidence: float = Field(ge=0.0, le=1.0, description="Overall mathematical confidence score [0.0 - 1.0]")
    evidence_references: List[EvidenceChunkPacket] = Field(default_factory=list, description="Compact peer-reviewed and institutional evidence chunks (5-8 max)")
    geographic_relevance: str = Field(default="globally_relevant", description="Geographic and biome applicability context")


class EcologicalFindingsRequest(BaseModel):
    """Request payload for the end-to-end Ecological Reasoning & Findings Pipeline (Phase 9)."""

    model_config = ConfigDict(extra="forbid")

    text_description: Optional[str] = Field(
        default=None,
        description="Free-form natural language description of observed site conditions or environmental parameters",
    )
    state: Optional[EnvironmentalState] = Field(
        default=None,
        description="Pre-structured EnvironmentalState (optional; can be merged with text extract and datasets)",
    )
    latitude: Optional[float] = Field(
        default=None,
        ge=-90.0,
        le=90.0,
        description="Latitude coordinate in decimal degrees [-90.0, 90.0]",
    )
    longitude: Optional[float] = Field(
        default=None,
        ge=-180.0,
        le=180.0,
        description="Longitude coordinate in decimal degrees [-180.0, 180.0]",
    )
    region: Optional[str] = Field(
        default=None,
        description="Explicit region override or hint (e.g. 'Western Ghats', 'Amazon Basin')",
    )
    ecosystem: Optional[str] = Field(
        default=None,
        description="Explicit ecosystem override or hint (e.g. 'tropical_forest', 'semi_arid', 'savanna')",
    )
    enrich_from_datasets: bool = Field(
        default=True,
        description="If True, query authoritative datasets to populate missing environmental variables",
    )
    overwrite_user_values: bool = Field(
        default=False,
        description="If True, overwrite user values with dataset values. If False (default), user values take precedence.",
    )
    allow_synthetic_fallback: bool = Field(
        default=True,
        description="Allow synthetic fallback if coordinates are outside authoritative extract boundaries",
    )
    top_k_evidence: int = Field(
        default=5,
        ge=1,
        le=10,
        description="Maximum number of evidence chunks per finding",
    )


class EcologicalFindingsResponse(BaseModel):
    """Comprehensive response from the Ecological Reasoning & Findings Pipeline."""

    model_config = ConfigDict(extra="forbid")

    canonical_state: EnvironmentalState = Field(description="Harmonized, validated EnvironmentalState incorporating user and dataset inputs")
    provenance_map: Dict[str, VariableProvenance] = Field(
        default_factory=dict,
        description="Per-variable provenance mapping detailing data source organizations, licenses, and dates",
    )
    variables_status: List[VariableStatus] = Field(
        default_factory=list,
        description="Complete list of all environmental variables classified as observed, dataset-derived, or unknown",
    )
    observed_user_metrics_count: int = Field(description="Number of metrics supplied directly by user or parsed from text")
    dataset_derived_metrics_count: int = Field(description="Number of metrics enriched from authoritative datasets")
    unknown_metrics_count: int = Field(description="Number of metrics with insufficient information (None)")
    findings: List[EcologicalFinding] = Field(default_factory=list, description="Structured multi-metric ecological findings")
    total_findings_count: int = Field(description="Total count of ecological findings identified")
    conflicts_detected: List[ConflictReport] = Field(default_factory=list, description="List of detected data discrepancies or mismatches")
    has_conflicts: bool = Field(default=False, description="True if any data or geographic conflicts were identified")
    overall_confidence_score: float = Field(ge=0.0, le=1.0, description="Mean confidence across all findings penalized for conflicts")
    system_limitations: List[str] = Field(default_factory=list, description="Explicit caveats, uncertainty notes, and scientific boundaries")
    evaluation_timestamp: str = Field(description="ISO timestamp of evaluation")
